github.com:
    git_protocol: ssh
    users:
        splixx05:
            oauth_token: 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
    user: splixx05
    oauth_token: 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
