[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number designating the VT.
vt = 1

[default_session]
command = "tuigreet --cmd hypr-run -r --asterisks --time --greeting 'Log in to nemesis' --theme 'border=black;greet=cyan;prompt=grey;action=cyan;button=white;time=cyan;container=black;input=grey;'" 
user = "greeter"
