[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#bec2d3", italic = true }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#0a0e21", bg = "#095fa2", bold = true }
find_position = { fg = "#0a0e21", bg = "#095fa2", bold = true }

# Marker
marker_copied   = { fg = "#73daca", bg = "#73daca" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#bb9af7", bg = "#bb9af7" }
marker_selected = { fg = "#095fa2", bg = "#095fa2" }

# Tab
tab_active   = { fg = "#c0caf5", bg = "#292e42" }
tab_inactive = { fg = "#3b4261", bg = "#1a1b26" }
tab_width    = 1

# Count
count_copied   = { fg = "#c0caf5", bg = "#41a6b5" }
count_cut      = { fg = "#c0caf5", bg = "#db4b4b" }
count_selected = { fg = "#c0caf5", bg = "#3d59a1" }

# Border
border_symbol = "│"
border_style  = { fg = "#bec2d3" }

[mode]
normal_main = { fg = "#15161e", bg = "#289ddf", bold = true }
normal_alt  = { fg = "#289ddf", bg = "#3b4261" }

select_main = { fg = "#15161e", bg = "#bb9af7", bold = true }
select_alt  = { fg = "#bb9af7", bg = "#3b4261" }

unset_main  = { fg = "#15161e", bg = "#9d7cd8", bold = true }
unset_alt   = { fg = "#9d7cd8", bg = "#3b4261" }

[status]
# separator_open    = ""
#separator_open    = ""
# separator_close   = ""
#separator_close   = ""
separator_close   = "│"
separator_open   = "│"
separator_style = { fg = "#095fa2", bg = "#095fa2" }

progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#1a1b26" }
progress_error  = { fg = "#f7768e" }

perm_type  = { fg = "#289ddf" }
perm_read  = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec  = { fg = "#9ece6a" }
perm_sep   = { fg = "#414868" }

[pick]
border   = { fg = "#27a1b9" }
active   = { fg = "#c0caf5",  bg = "#283457" }
inactive = { fg = "#c0caf5" }

[input]
border   = { fg = "#0db9d7" }
title    = { fg = "#0db9d7" }
value    = { fg = "#c0caf5" }
# selected = { bg = "#283457" }

[completion]
border   = { fg = "#0db9d7" }
active   = { fg = "#c0caf5", bg = "#283457" }
inactive = { fg = "#c0caf5" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "#27a1b9" }
title   = { fg = "#27a1b9" }
hovered = { fg = "#c0caf5", bg="#283457" }

[which]
cols            = 3
mask            = { bg = "#16161e" }
cand            = { fg = "#7dcfff" }
rest            = { fg = "#289ddf" }
desc            = { fg = "#bb9af7" }
separator       = " ➜ "
separator_style = { fg = "#3ea5d9" }

[confirm]
border  = { fg = "#0db9d7" }
title   = { fg = "#27a1b9" }
content = {}
list    = {}
btn_yes = { bg = "#283457" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border  = { fg = "#27a1b9" }
title   = { fg = "#27a1b9" }

[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#e0af68" }
title_error = { fg = "#db4b4b" }

icon_error = ""
icon_warn = ""
icon_info = ""

[help]
on      = { fg = "#9ece6a" }
run     = { fg = "#bb9af7" }
hovered = { bg = "#292e42" }
footer  = { fg = "#c0caf5", bg = "#1a1b26" }

[filetype]

rules = [
	{ mime = "image/*", fg = "#e0af68" },
	{ mime = "{audio,video}/*", fg = "#bb9af7" },
	{ mime = "application/*zip", fg = "#f7768e" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f7768e" },
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7dcfff" },

# Empty files
	# { mime = "inode/x-empty", fg = "#f7768e" },

# Special files
	{ name = "*", is = "orphan", bg = "#f7768e" },
	{ name = "*", is = "exec"  , fg = "#9ece6a" },

	# Fallback
	{ name = "*/", fg = "#289ddf" }
]
