local c = require("res.utils.colors")
local set_hl = vim.api.nvim_set_hl

set_hl(0, "WhichKey", { fg = c.prim.main, bg = c.bg.slate })
set_hl(0, "WhichKeyBorder", { fg = c.fg.main, bg = c.bg.slate })
set_hl(0, "WhichKeyDesc", { fg = c.fg.main, bg = c.bg.slate })
set_hl(0, "WhichKeyGroup", { fg = c.fg.main, bg = c.bg.slate })
set_hl(0, "WhichKeyIconAzure", { fg = c.prim.main, bg = c.bg.slate })
set_hl(0, "WhichKeyIconBlue", { fg = c.acc.blue, bg = c.bg.slate })
set_hl(0, "WhichKeyIconCyan", { fg = c.acc.cyan, bg = c.bg.slate })
set_hl(0, "WhichKeyIconGrey", { fg = c.tone.grey, bg = c.bg.slate })
set_hl(0, "WhichKeyIconOrange", { fg = c.acc.orange, bg = c.bg.slate })
set_hl(0, "WhichKeyIconPurple", { fg = c.acc.violet, bg = c.bg.slate })
set_hl(0, "WhichKeyIconRed", { fg = c.acc.red, bg = c.bg.slate })
set_hl(0, "WhichKeyIconYellow", { fg = c.acc.yellow, bg = c.bg.slate })
set_hl(0, "WhichKeyNormal", { fg = c.fg.main, bg = c.bg.slate })
set_hl(0, "WhichKeySeparator", { fg = c.acc.violet, bg = c.bg.slate })
set_hl(0, "WhichKeyTitle", { fg = c.prim.main, bg = c.bg.slate })
set_hl(0, "WhichKeyValue", { fg = c.acc.magenta, bg = c.bg.slate })
