#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch"
CFG="$HOME/.config/eww/"
EWW=$(which eww)

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
	${EWW} daemon
	sleep 3
fi

## Open widgets
run_eww() {
	${EWW} --config "$CFG" open-many \
		system \
		clock \
		sleep \
		reboot \
		poweroff \
		folders
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
		system clock \
		sleep reboot poweroff folders
	rm "$FILE"
fi
