
[pyprland]
plugins = ["expose"]

[expose]
include_special = false

# [scratchpads.term]
# animation = "fromTop"
# command = "kitty --class kitty-scratchpad"
# class = "kitty-scratchpad"
# size = "80% 60%"
