alias zsh.conf='yazi "$HOME/.zsh/"'
alias hypr.conf='yazi "$HOME/.config/hypr"'
alias kitty.conf='yazi "$HOME/.config/kitty"'
alias way.conf='yazi "$HOME/.config/waybar"'
alias nvim.conf='yazi "$HOME/.config/nvim"'
alias tmux.conf='yazi "$HOME/.config/tmux"'
alias eww.conf='yazi "$HOME/.config/eww"'
